* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Mulberry
Шелковица.
* Obligatory
Обязательный.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Сулема
Mercuric chloride. Neurotoxic.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Bagel
Бублик.
* Invective
Critic is the strict sence.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
* CliffsNotes
Short good description of the literature.
Initially CliffNotes are a company and a series of study guides available firstly in the US.
* Abridgment
A shortened version of a larger work.
* Штуцер
1. Ружье с укороченным нарезным стволом через которое и заряжающееся.
Штуцер - неметское слово, позже в обиходе появились слова винтовая пищаль и винтовка.

2. Короткая соединительная труба.
* Хлопуша
Врунишка.
* Ирокез
1. Индеец группы
2. Причёска
* Накипень
Бугор льда из ключа/теплого ключа.
* Фронтон
Венчание фронтальной стены фасада здания, начинаеться за карнизом, обычно теругольное реже - полуциркульное.
* Поносность
Дальнобойность.
* Сполитично
Удобно.
* Орочоне
Некоторые.
* Шустование
Сглаживание дула в рушьях.
* Crepuscular
Cумеречно.
* Excavate
/ˈɛkskəveɪt/
Remove earth from an area to find buried.
* Квартерон
Четверть генов чёрной крови.
* Манишка
Нагрудная вставка в мужской и женской одежде, которая видна в вырезе жилета, фрака или дамского платья.
* Safeword
No comments.
* Flash flood
Внезапный ливневый затапливающий паводок.
* To hoard
Accumulate (money or valued objects) and hide / store away.
* Hardship
Severe suffering or privation.
* Privation
State in which essentials for well-being are lacking.
* Capricious
Changing according to no discernible rules; unpredictable
* Discern
Recognize or find out, distinguish (someone or something) with difficulty by sight or with the other senses.
* Wedlock
The state of being married.
* The Holocene
Current geneological epoch. Began approximately 11,650 cal years before present, after the last glacial period.
* Malcontent
Dissatisfied, complaining, trouble, rebellious.
* Rousing
Воодушевляющий.
Exciting; stirring.
* Rabble
Сброд, чернь.
A disorderly crowd; a mob.
* Contempt
The feeling that a person or a thing is beneath consideration, worthless, or deserving scorn.
* Scorn
Презрение.
* Derision
/dɪˈrɪʒ(ə)n/
Осмеяние.
Contemptuous ridicule or mockery.
* Eggnog
A drink made from a mixture of beaten eggs, cream, and flavorings, often with alcohol
* Malfeasance
Злодеяние, должностоное преступление.
* Indiginous
Mестный.
Native.
* Infatuated
Be inspired with an intense but short-lived passion or admiration for
* Creole
Ethnic groups which originated during the colonial-era from racial mixing between Europeans and non-European peoples.
* Nouveau
Newly arrived/developed.
* Salient
The most noticeable/important.
* Torpor
State of physical or mental inactivity; lethargy.
* Callousness
/ˈkaləsnəs/
Бессердечность.
Insensitive and cruel disregard for others.
* Jot
Write (something) down quickly
* Avid
Алчный.
* Shunned
Persistently avoided.
* Shyster
/ˈʃʌɪstə/
A person who uses unscrupulous, fraudulent, or deceptive methods in business.
* Turgid
/ˈtəːdʒɪd/
1. Swollen and distended or congested. опухший
2. (of language or style) tediously pompous or bombastic. напыщенный
* Macabra
/məˈkɑːbr(ə)/
Disturbing because concerned with a fear of death.
* Heed
Внимание.
* Corporeal
/kɔːˈpɔːrɪəl/
Relating to a person's body, especially as opposed to spirit.
Having a body. Material.
* Compartment
/kəmˈpɑːtm(ə)nt/
Separate section or part of a structure or container.
* Precarious
/prɪˈkɛːrɪəs/
Not securely held or in position; dangerously likely to fall or collapse.
Сомнительно, ненадёжно.
* Scaffold
Cтроительные леса.
* Gazebo
Беседка, альтанка.
