* Abridgment
A shortened version of a larger work.
* Accoutrement
Accoutrement - /əˈkuːtəm(ə)nt,əˈkuːtrəm(ə)nt/ - личное снаряжение.
* Acerbic
Acerbic - /əˈsəːbɪk/ - (especially on a style of speaking) sharp and forthright.
* Alacrity
Alacrity - /əˈlakrɪti/ - brisk and cheerful readiness.
* Amok
Amok - . - killing madness.
* Ancillary
Ancillary - /anˈsɪləri/ - providing necessary support to the primary activities or operation of an organization, system, etc.
* Anglicanism
Anglicanism - . - Church of England, that supports the belief that God is a ruler of the country and Monarch had power descended direcly from the God.
* Anguish
Anguish - /ˈaŋɡwɪʃ/ - особенно остаря тоска.
* Anxious
Anxious - /ˈaŋ(k)ʃəs/ - feeling or showing worry, nervousness, or unease about something with an uncertain outcome.
* Apothecary
Apothecary - a person who prepares medicines and drugs from components.
* Arboretum
Arboretum - дендрарий.
* Arson
Arson - /ˈɑːs(ə)n/ - the act of deliberately setting on fire.
* Artisan
A craftsman of the skilled trade.
* Asinine
Asinine - /ˈasɪnʌɪn/ - глупый.
* Aspiration
Aspiration - /aspəˈreɪʃ(ə)n/ - an ambition of achieving something.
* Auxiliary
Auxiliary - /ɔːɡˈzɪlɪəri,ɒɡˈzɪlɪəri/ - всомогательный.
* Avid
Алчный.
* Bagel
Бублик.
* Bailey
Bailey - . - in fortification is a courtyard enclosed by the wall.
* Banister
Banister - .  - перила, баллюстрада.
* Befriend
Befriend - become a friend with, especially help people.
* Benevolent
Benevolent - /bɪˈnɛv(ə)l(ə)nt/ - доброжелательный.
* Benign
Benign - /bɪˈnʌɪn/ - (of disease) not harmful in effect. Gentle and kind.
* Betrothal
Betrothal - /bɪˈtrəʊð(ə)l/ - помолвка.
* Bigotry
Bigotry - /ˈbɪɡətri/ - blind fanatism.
* Bile
Желчь.
* Bog
Bog - /bɒɡ/ - топь.
* Bogus
Bogus - /ˈbəʊɡəs/ - false that presented as genuine true.
* Brandish
Brandish - /ˈbrandɪʃ/ - размахивать.
* Brooding
Brooding - /ˈbruːdɪŋ/ - высиживать (яйца), быть глубоко задумчивым.
* Buck
Buck - /bʌk/ - брыкаться, самец.
* Buckle
Buckle - /ˈbʌk(ə)l/ - to bend and give way.
* Buffet
Buffet - . - (especially of wind or waves) strike repeatedly and violently; batter.
* Bullpen
Bullpen - /ˈbʊlpɛn/ - кутузка.
* Burpee
Burpee - /ˈbəːpiː/ - a exercise consisting of a squat thrust made from and ending in a standing position.
* Burrow
Burrow - /ˈbərō/ - нора.
* Buttermilk
Пахта.
* Callousness
/ˈkaləsnəs/
Бессердечность.
Insensitive and cruel disregard for others.
* Camomile
Camomile - ромашка.
* Candid
Truthful and straightforward.
* Capricious
Changing according to no discernible rules; unpredictable
* Caress
Caress - /kəˈrɛs/ - ласкать, приласкивать.
* Carnal
Carnal - /ˈkɑːn(ə)l/ - плотский.
* Changeling
Changeling - /ˈtʃeɪn(d)ʒlɪŋ/ - подменыш.
* Chivalrous
Chivalrous - /ˈʃɪv(ə)lrəs/ - рыцарский.
* Chump
Chump - /tʃʌmp/ - stupid and easily deceived.
* Cinder block
Cinder block - /ˈsindər/ - шлако блок.
* Clearing
Clearing - /ˈklɪərɪŋ/ - open space in forest, especially cleared for cultivation.
* CliffsNotes
Short good description of the literature.
Initially CliffNotes are a company and a series of study guides available firstly in the US.
* Coerce
Coerce - /kəʊˈəːs/ - принуждать.
* Compartment
/kəmˈpɑːtm(ə)nt/
Separate section or part of a structure or container.
* Compartmentalize
Compartmentalize - /kɒmpɑːtˈmɛnt(ə)lʌɪz/ - divide into discrete sections or categories.
* Confounded
Confounded - /kənˈfaʊndɪd/ - cause surprise or confusion in (someone), especially by not according with their expectations.
* Congruence
Congruence - /ˈkɒŋɡrʊəns/ - согласованность.
* Congruence
Congruence - /ˈkɒŋɡrʊəns/ - harmony, agreement, compatibility.
* Conscientiousness
Conscientiousness - /kɒnʃɪˈɛnʃəsnəs/ - добросовесность и сознательность.
* Contempt
The feeling that a person or a thing is beneath consideration, worthless, or deserving scorn.
* Contentment
Contentment - /kənˈtɛntm(ə)nt/ - довольство.
* Contrite
Contrite - /kənˈtrʌɪt,ˈkɒntrʌɪt/ - сокрушаться, каяться.
* Cootie
Платяная вошь.
* Corporeal
/kɔːˈpɔːrɪəl/
Relating to a person's body, especially as opposed to spirit.
Having a body. Material.
* Courtship
Courtship - /ˈkɔːtʃɪp/ - a period of a couple develop before getting married.
* Cranium
Cranium - /ˈkreɪnɪəm/ - череп.
* Creole
Ethnic groups which originated during the colonial-era from racial mixing between Europeans and non-European peoples.
* Crepuscular
Cумеречно.
* Cunning
Cunning - . - skill in achieving one's ends by deceit.
* Deadnaming
Deadnaming - . - use name that person changes.
* Debacle
Debacle - /deɪˈbɑːk(ə)l/ - ignominious failure.
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Defer
Defer - /dɪˈfəː/ - postpone.
* Defiance
Defiance - /dɪˈfʌɪəns/ - открытое сопротивление.
* Dementor
Dementor - . - evil and fearsome creature.
* Denizen
Denizen - /ˈdɛnɪz(ə)n/ - обитатель места.
* Derision
/dɪˈrɪʒ(ə)n/
Осмеяние.
Contemptuous ridicule or mockery.
* Dilligent
Dilligent - /ˈdɪlɪdʒ(ə)nt/ - старательно.
* Discern
Recognize or find out, distinguish (someone or something) with difficulty by sight or with the other senses.
* Discordant
Discordant - /dɪˈskɔːd(ə)nt/ - рассогласованный.
* Dispersal
Dispersal - /dɪˈspəːs(ə)l/ - распространение, рассеивание, рассредоточение.
* Dissolution
Dissolution - closing down or dismissal of an assembly, partnership, or official body.
Dissolution - debauched living; dissipation.
* Diuretic
Diuretic - . - substance that increases the amount of water and salt expelled.
* Eavesdrop
Secretly listen to a conversation.
* Efficacious
Efficacious - /ˌɛfɪˈkeɪʃəs/ - having the power to produce a desired effect.
* Eggnog
A drink made from a mixture of beaten eggs, cream, and flavorings, often with alcohol
* Embezzler
Embezzler - who takes company money for his or her own purposes.
* Epicureanism
Epicureanism - Epicurus believed that what he called "pleasure" (ἡδονή) was the greatest good, but that the way to attain such pleasure was to live modestly, to gain knowledge of the workings of the world, and to limit one's desires. This would lead one to attain a state of tranquility (ataraxia) and freedom from fear as well as an absence of bodily pain (aponia). The combination of these two states constitutes happiness in its highest form.
* Epistemology
Epistemology - /ɪˌpɪstɪˈmɒlədʒi,ɛˌpɪstɪˈmɒlədʒi/ - the theory of knowledge, especially with regard to its methods, validity, and scope, and the distinction between justified belief and opinion.
* et al.
et al. - .  - scholarly abbreviation of the Latin /et alia/ (“and others”).
* Excavate
/ˈɛkskəveɪt/
Remove earth from an area to find buried.
* Expat
Expat - person taking up residency in another country.
* Facetious
/fəˈsiːʃəs/
Facetious - treating serious issues with deliberately inappropriate humor; flippant.
* Fathometer
Fathometer - /faˈðɒmɪtə/ - эхолот.
* Feisty
Feisty - /ˈfʌɪsti/ - (of a person, typically one who is relatively small) lively, determined, and courageous.
* Felicitations
Felicitations - /fəlɪsɪˈteɪʃ(ə)nz/ - Words expressing praise for an achievement or good wishes on a special occasion.
* Flash flood
Внезапный ливневый затапливающий паводок.
* Flay
Flay - strip the skin.
* Foil
Foil - prevent something considered wrong from succeeding.
* Formidable
Formidable - /ˈfɔːmɪdəb(ə)l,fəˈmɪdəb(ə)l/ - inspiring fear or respect through being impressively large, powerful, intense, or capable.
* Formulaic
Formulaic - /ˌfɔːmjʊˈleɪɪk/ - шаблонный.
* Forthright
Forthright - /ˈfɔːθrʌɪt,fɔːθˈrʌɪt/ - (of a person, their manner or speech) direct and outspoken.
* Fortuitous
Fortuitous - /fɔːˈtjuːɪtəs/ - by a lucky chance.
* Freebie
Freebie - /ˈfriːbi/ - a thing given free of charge. Халява.
* Fringe
Fringe - /frɪn(d)ʒ/ - дополнательный край, чёлка, бахрома.
* Futility
Futility - /fjʊˈtɪlɪti,fjuːˈtɪlɪti/ - pointlessness or uselessness.
Тщетность.
* Gallant
Gallant - /ˈɡal(ə)nt/ - brave, heroic, grand impressive, attentively charming and chivalrous to women.
* Gallbladder
Желчный пузырь.
* Gazebo
Беседка, альтанка.
* Ghastly
Ghastly - /ˈɡɑːs(t)li/ - causing great horror.
* Gist
Gist - . - the substance of a speech, text, action.
* Gnarly
Gnarly - . - slang term for something grotesque, yet awesomely extreme. Used in bad and good cases.
* Gregarious
Gregarious - /ɡrɪˈɡɛːrɪəs/ - happily living togather.
* Grovel
Grovel - /ˈɡrɒv(ə)l,ˈɡrʌv(ə)l/ - ползать, пресмыкаться, унижаться.
* Hail
Hail - /heɪl/ - град, в т.ч. звук.
* Handspring
Handspring - /ˈhan(d)sprɪŋ/ - колесо (елемент).
* Hardship
Severe suffering or privation.
* Hardwood
Hardwood - твердые породы деррева.
* Hedonism
 Hedonism - /ˈhiːd(ə)nɪz(ə)m,ˈhɛːd(ə)nɪz(ə)m/ - the pursuit of pleasure; sensual self-indulgence.
The ethical theory that pleasure (in the sense of the satisfaction of desires) is the highest good and proper aim of human life.
* Heed
Внимание.
* Heist
Кража.
* Hense
Следовательно.
Therefore.
* Hereditary
Hereditary - /hɪˈrɛdɪt(ə)ri/ - наследственный.
* Hindsight
Understanding of a situation or event only after it has happened or developed.
* Id
The part of the mind in which innate instinctive impulses and primary processes are manifest.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
* Ignominious
Ignominious - /ˌɪɡnəˈmɪnɪəs/ - causing, deserving public shame or disgrace.
* IIRC
IIRC - . - If I Recall Correctly.
* Illustrious
Illustrious - famous, well known, respected, and admired for past achievements.
* Immaculate
Immaculate - /ɪˈmakjʊlət/ - безукоризненный.
* Incomprehensible
Incomprehensible - /ˌɪnkɒmprɪˈhɛnsɪb(ə)l/ - непостижимо, непонятно, неразборчиво.
* Incomprehensible
Incomprehensible - /ˌɪnkɒmprɪˈhɛnsɪb(ə)l/ - непонятно, непостижимый.
* Indefinite
Indefinite - /ɪnˈdɛfɪnət/ - неопределенный или неограниченный. Размытый.
* Indiginous
Mестный.
Native.
* Indoctrinate
Indoctrinate - /ɪnˈdɒktrɪneɪt/ - внушать.
* Infatuated
Be inspired with an intense but short-lived passion or admiration for
* Innocuous
/ɪˈnɒkjʊəs/
Safe and unharmful.
* Insatiable
Insatiable - /ɪnˈseɪʃəb(ə)l/ - impossible to satisfy.
* Instrumental violence
Instrumental violence - . - is goal-oriented aggression or violence that occurs as a by-product of an individual's attempting to achieve a superordinate goal.
* Insulary
Insulary - /in·​su·​lary/ - archaic: islander, insular.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Invaluable
/ɪnˈvaljʊ(ə)b(ə)l/
Invaluable - extremely useful; indispensable.
* Invective
Critic is the strict sence.
* Jaded
Jaded - /ˈdʒeɪdɪd/ - bored, lacking enthusiasm, after having had too much of something.
* Jinx
Jinx - /dʒɪŋks/ - cursed, bring bad luck.
* Jot
Write (something) down quickly
* Kinesthesia
Kinesthesia - /ˌkɪnɪsˈθiːzɪə,/ - external body awareness.
* Languid
Languid -  /ˈlaŋ-gwəd/ - сильно уставши.
* Lass
Lass - /las/ - tender calling for a young women.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Levy
Levy - /ˈlɛvi/ - enforced demand (a tax, fee, fine, duty).
* Loam
/ləʊm/
Loam - fertile soil of clay and sand containing humus.
* Macabra
/məˈkɑːbr(ə)/
Disturbing because concerned with a fear of death.
* Malcontent
Dissatisfied, complaining, trouble, rebellious.
* Malfeasance
Злодеяние, должностоное преступление.
* Man of the cloth
Man of the cloth - .  - clergymen.
* Marooned
Marooned - .  - isolated, abandoned.
* Materia medica
Materia medica - сумма знаний о лечебный свойствах веществ.
* Matte
Matte - /mat/ - штейн, матовая поверхность, маска, каше, декорация.
* Maw
Maw - /mɔː/ - пасть.
* Mischievous
/ˈmɪstʃɪvəs/
Вредный.
* Misogynist
Misogynist - /mɪˈsɒdʒ(ə)nɪst/ - женоненавистник.
* Molar
Molar - /ˈməʊlə/ - моляр, коренной зуб.
* Morrow
/ˈmɒrəʊ/
Morrow - the time following the event. The following day. The near future.
* Mulberry
Шелковица.
* Mull
/mʌl/
Mull - think about (a fact, proposal, or request) deeply and at length.
* Mulligan
Mulligan - /dʒɪŋks/ - is a second chance to perform an action, usually after the first chance went wrong through bad luck or a blunder. 
* Munition
Munition - /mjʊˈnɪʃ(ə)n/ - военное снаряжение.
* Nag
Nag - /naɡ/ - пилить, ворчать.
* Neologism
A newly coined word or expression.
* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Nonchalant
Nonchalant - /ˈnɒnʃ(ə)l(ə)nt/ - беспечно.
* Nouveau
Newly arrived/developed.
* Numinous
Numinous - .  - mysterious feeling surpassing understanding and comprehension.
* Obligatory
Обязательный.
* Oliebol
Oliebol is a traditional Dutch and Belgian food. Oliebollen are a variety of dumpling made by using an ice cream scoop or two spoons to scoop a certain amount of dough and dropping the dough into a deep fryer filled with hot oil.
* Orchard
Orchard - .  - фруктовый сад.
* Orchid
Orchid - . - орхидея.
* Outspoken
Outspoken - /aʊtˈspəʊk(ə)n/ - откровенный, прямой.
* Panspermia
Panspermia - . - principle of life spreading through cosmos due to luck anabiosis and chunks of matter traveling through space.
* Paucity
Paucity - /ˈpɔːsɪti/ - малочисленность.
* Perch
Жердь, окунь.
* Peril
Peril - direct serious danger.
* Perverse
Perverse - /pəˈvəːs/ - извращенный.
* Pet peeve
Something that a particular person finds especially annoying.
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Portmanteau
Portmanteau - /pɔːtˈmantəʊ/ - word formation from blending words and meaning of two others. Motel, brunch, podcast, infomertial.
* Pow wow
Pow wow - . - (from Native Amirican) social gathering. Powwaw - spiritual leader.
* Precarious
/prɪˈkɛːrɪəs/
Not securely held or in position; dangerously likely to fall or collapse.
Сомнительно, ненадёжно.
* Preemie
Preemie - /ˈprēmē/ - prematurely born baby.
* Preposterous
Preposterous - /prɪˈpɒst(ə)rəs/ - utterly absurd or ridiculous.
* Privation
State in which essentials for well-being are lacking.
* Proprioception
Proprioception - /ˌprə(ʊ)prɪəˈsɛpʃn/ - awareness of the body.
* Prowl
Prowl - /praʊl/ - рыскать.
* Pugnacious
Pugnacious - /pʌɡˈneɪʃəs/ - eager to fight, quick to argue, quarrel.
* Pungent
Pungent - /ˈpʌn(d)ʒ(ə)nt/ - having a sharply strong taste or smell.
* Quagmire
Quagmire - /ˈkwaɡmʌɪə/ - трясина.
* Rabble
Сброд, чернь.
A disorderly crowd; a mob.
* Ravenous
Extremely hungry.
* Reciprocity
Reciprocity - /ˌrɛsɪˈprɒsɪti/ - exchanging things with others for mutual benefit.
* Reconnaissance
Reconnaissance - /rɪˈkɒnɪs(ə)ns/ - military observation of a region to locate an enemy or ascertain strategic features.
* Relinquish
Relinquish - /rɪˈlɪŋkwɪʃ/ - уступить.
* Reluctant
Reluctant - /rɪˈlʌkt(ə)nt/ - неохотно.
* Resfeber
Resfeber - .  - excitement and fear before journey.
* Resilient
Resilient - /rɪˈzɪlɪənt/ - able to withstand, or quick to recover.
* Resin
Resin - /ˈrɛzɪn/ - смола, канифоль.
* Resourceful
Resourceful - /rɪˈsɔːsfʊl,rɪˈzɔːsfʊl/ - having the ability to find quick and clever ways to overcome difficulties. Находчивый.
* Rhubarb
Rhubarb - ревень.
* Rousing
Воодушевляющий.
Exciting; stirring.
* Rove
Rove - . - ровница, прогуливаться, путешествовать.
* Ruth
Ruth - /ruːθ/ - жалость, милосердие, сострадание.
* Safeword
No comments.
* Sage
Sage - . - шалфей, глубокомысленный.
* Salient
The most noticeable/important.
* Sandpiper
Sandpiper - .  - small shore bird with long beak that filters the sand.
* Savant
Savant - . - a person of learning. Especially one with detailed knowledge in specialized field. 
* Scaffold
Cтроительные леса.
* Scant
Scant - scant - скудный.
* Scorn
Презрение.
* Scrumptious
Scrumptious - /ˈskrʌm(p)ʃəs/ - extremely tasty; delicious.
* Secular
Secular - /ˈsɛkjʊlə/ - (of clergy) not subject to or bound by religious rule; not belonging to or living in a monastic or other order.
* Settee
Settee - /sɛˈtiː/ - long couch.
* Shrill
Shrill - /ʃrɪl/ - high-pitched and piercing.
* Shrub
Shrub - /ʃrʌb/ - кустарник.
* Shunned
Persistently avoided.
* Shyster
/ˈʃʌɪstə/
A person who uses unscrupulous, fraudulent, or deceptive methods in business.
* Sideburns
Sideburns - . - a strip of hair grown by a man down each side of the face in front of his ears.
* Silicon
Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre; and it is a tetravalent metalloid and semiconductor.
* Silicone
Silicones, also known as polysiloxanes, are polymers that include any inert, synthetic compound made up of repeating units of siloxane, which is a chain of alternating silicon atoms and oxygen atoms, combined with carbon, hydrogen, and sometimes other elements. They are typically heat-resistant and either liquid or rubber-like, and are used in sealants, adhesives, lubricants, medicine, cooking utensils, and thermal and electrical insulation.
* Sinister
Sinister - /ˈsi-nə-stər/ - threatening harm, trouble, evil; ominous.
* Skittish
Skittish - /ˈskɪtɪʃ/ - (of an animal) nervous or excitable; easily scared. (of a person) playfully frivolous or unpredictable.
* Slander
Slander - /ˈslɑːndə/ - клевета.
* Sombre
Sombre - /ˈsɒmbə/ - dark&dull in tone, convaying a feeling of deep sadness.
* Sophomore
Sophomore - /ˈsɑːfmɔːr/ - второкурсник, самоуверенный невежда.
* Spitball
Throw out (a suggestion) for discussion.
* Stail
Stail - /steɪl/ - old form for Stale - no longer fresh.
* Stern
Stern - корма.
* Succinct
Succinct - /sə(k)ˈsiNG(k)t/ - consice, краткий, сжатый.
* Succulent
Succulent - /ˈsʌkjʊl(ə)nt/ - 1. tender, juicy, tasty. 2. (of a plant, especially a xerophyte) having thick fleshy leaves or stems adapted to storing water.
* Sufism
Sufism - . - "Islamic mysticism", "the inward dimension of Islam".
* Surmise
Surmise - /səˈmʌɪz/ - suppose that something is true without having evidence to confirm it.
* Swoon
Swoon - /swuːn/ - faint from extreme emotion.
* Tardigrade
Tardigrade - /ˈtɑːrdɪˌɡreɪd/ - a small living organism also known as water bears that are the most abundant and most durable form of life. Can go into anabiosis in the space.
* Tardy
Tardy - /ˈtɑːdi/ - запоздалый.
* Terse
Terse - sparing in the use of words; abrupt.
Краткий
* The Holocene
Current geneological epoch. Began approximately 11,650 cal years before present, after the last glacial period.
* Thunk
Thunk - /θʌŋk/ - преобразователь.
* Tick off
Tick off - set a done mark, or to annoy.
* To hoard
Accumulate (money or valued objects) and hide / store away.
* Torpor
State of physical or mental inactivity; lethargy.
* Tranquility
Tranquility - /traŋˈkwɪlɪti/ - the quality state of being in a good state.
* Travail
Travail - /ˈtraveɪl/ - тяжелый труд.
* Truism
Truism - a statement that is obviously true and says nothing new or interesting.
* Turgid
/ˈtəːdʒɪd/
1. Swollen and distended or congested. опухший
2. (of language or style) tediously pompous or bombastic. напыщенный
* Ubiquitous
Ubiquitous - present, appearing, or found everywhere.
Вездесущий, повсеместный.
* Uncanny valley
Uncanny valley - . - unease or revulsion on seing a created face.
* Utter
Utter - /ˈʌtə/ - make a sound with one's voice.
* Veer
Veer - /vɪə/ - a sudden change of direction. Вираж.
* Venison
Venison - is the meat of a deer.
* Vicarious
Experienced through the feelings or actions of another person.
* Vigilant
Vigilant - /ˈvɪdʒɪl(ə)nt/ - carefully watch.
* Visceral
Visceral - bringing deep invard emotional feelings.
* Volant
Volant - .  - having a power or engaged in flying.
* Wanderlust
Wanderlust - . - storong desire to rove.
* Wart
Wart - /wôrt/ - бородавка.
* Wedlock
The state of being married.
* Whimsical
Whimsical - /ˈwɪmzɪk(ə)l/ - причудливо капризный.
* Wicked
Wicked - /ˈwɪkɪd/ - evil or morally wrong. Злой, безравственный.
* Zesty
Zesty - . - spicy, fun and exciting. Crowd, party, food - everything can be zasty.
* Аустерия
Аустерия - от лат. /austeria/ трактир - модный трактир времени Петра.
* Вяхирь
Вяхирь - . - лесной голубь.
* Деизм
Деизм - философское направление, признающее существование Бога и сотворение им мира, но отрицающее большинство сверхъестественных и мистических явлений.
* Имманентное
Имманентное - внутренне присущее тому или иному предмету, явлению или процессу свойство (закономерность).
Имманентное - неотьемлемая внутренняя деталь, остающийся внутри границ возможного опыта.
* Ирокез
1. Индеец группы
2. Причёска
* Квартерон
Четверть генов чёрной крови.
* Кондовый
Топорный, грубый, плотно-древесный.
* Манишка
Нагрудная вставка в мужской и женской одежде, которая видна в вырезе жилета, фрака или дамского платья.
* Накипень
Бугор льда из ключа/теплого ключа.
* Норовистый
Норовистый - очень своенравный характер.
* Орочоне
Некоторые.
* Поносность
Дальнобойность.
* Сполитично
Удобно.
* Сулема
Mercuric chloride. Neurotoxic.
* Фронтон
Венчание фронтальной стены фасада здания, начинаеться за карнизом, обычно теругольное реже - полуциркульное.
* Хлопуша
Врунишка.
* Штуцер
1. Ружье с укороченным нарезным стволом через которое и заряжающееся.
Штуцер - неметское слово, позже в обиходе появились слова винтовая пищаль и винтовка.

2. Короткая соединительная труба.
* Шустование
Сглаживание дула в рушьях.
* Thwart
Thwart - /θwɔːt/ - prevent something.
* Conjecture
Conjecture - /kənˈdʒɛktʃə/ - предположение.
* Апперцепция
Апперцепция - .  - /ad/ /perceptio/ элементы сознания становятся ясными и отчетливыми.
* Rife
Rife - /rʌɪf/ - изобилующий.
* Hortator
Hortator - .  - наставник.
* Plight
Plight - /plʌɪt/ - difficult situation.
* Staunch
Staunch - /stɔːn(t)ʃ/ - strong, firm, loyal in atitude or standing.
* Gullible :drill:
Gullible - /ˈɡʌləb(ə)l/ - черезчур доверчивый, простофиля.
