* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Mulberry
Шелковица.
* Obligatory
Обязательный.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Сулема
Mercuric chloride. Neurotoxic.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Bagel
Бублик.
* Invective
Critic is the strict sence.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
* CliffsNotes
Short good description of the literature.
Initially CliffNotes are a company and a series of study guides available firstly in the US.
* Abridgment
A shortened version of a larger work.
* Штуцер
1. Ружье с укороченным нарезным стволом через которое и заряжающееся.
Штуцер - неметское слово, позже в обиходе появились слова винтовая пищаль и винтовка.

2. Короткая соединительная труба.
* Хлопуша
Врунишка.
* Ирокез
1. Индеец группы
2. Причёска
* Накипень
Бугор льда из ключа/теплого ключа.
* Фронтон
Венчание фронтальной стены фасада здания, начинаеться за карнизом, обычно теругольное реже - полуциркульное.
* Поносность
Дальнобойность.
* Сполитично
Удобно.
* Орочоне
Некоторые.
* Шустование
Сглаживание дула в рушьях.
* Crepuscular
Cумеречно.
* Excavate
/ˈɛkskəveɪt/
Remove earth from an area to find buried.
* Квартерон
Четверть генов чёрной крови.
* Манишка
Нагрудная вставка в мужской и женской одежде, которая видна в вырезе жилета, фрака или дамского платья.
