* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Mulberry
Шелковица.
* Obligatory
Обязательный.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Сулема
Mercuric chloride. Neurotoxic.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Bagel
Бублик.
* Invective
Critic is the strict sence.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
* CliffsNotes
Short good description of the literature.
Initially CliffNotes are a company and a series of study guides available firstly in the US.
* Abridgment
A shortened version of a larger work.
* Штуцер
1. Ружье с укороченным нарезным стволом через которое и заряжающееся.
Штуцер - неметское слово, позже в обиходе появились слова винтовая пищаль и винтовка.

2. Короткая соединительная труба.
* Хлопуша
Врунишка.
* Ирокез
1. Индеец группы
2. Причёска
* Накипень
Бугор льда из ключа/теплого ключа.
* Фронтон
Венчание фронтальной стены фасада здания, начинаеться за карнизом, обычно теругольное реже - полуциркульное.
* Поносность
Дальнобойность.
* Сполитично
Удобно.
* Орочоне
Некоторые.
* Шустование
Сглаживание дула в рушьях.
* Crepuscular
Cумеречно.
* Excavate
/ˈɛkskəveɪt/
Remove earth from an area to find buried.
* Квартерон
Четверть генов чёрной крови.
* Манишка
Нагрудная вставка в мужской и женской одежде, которая видна в вырезе жилета, фрака или дамского платья.
* Safeword
No comments.
* Flash flood
Внезапный ливневый затапливающий паводок.
* To hoard
Accumulate (money or valued objects) and hide / store away.
* Hardship
Severe suffering or privation.
* Privation
State in which essentials for well-being are lacking.
* Capricious
Changing according to no discernible rules; unpredictable
* Discern
Recognize or find out, distinguish (someone or something) with difficulty by sight or with the other senses.
* Wedlock
The state of being married.
* The Holocene
Current geneological epoch. Began approximately 11,650 cal years before present, after the last glacial period.
* Malcontent
Dissatisfied, complaining, trouble, rebellious.
* Rousing
Воодушевляющий.
Exciting; stirring.
* Rabble
Сброд, чернь.
A disorderly crowd; a mob.
* Contempt
The feeling that a person or a thing is beneath consideration, worthless, or deserving scorn.
* Scorn
Презрение.
* Derision
/dɪˈrɪʒ(ə)n/
Осмеяние.
Contemptuous ridicule or mockery.
* Eggnog
A drink made from a mixture of beaten eggs, cream, and flavorings, often with alcohol
* Malfeasance
Злодеяние, должностоное преступление.
* Indiginous
Mестный.
Native.
* Infatuated
Be inspired with an intense but short-lived passion or admiration for
* Creole
Ethnic groups which originated during the colonial-era from racial mixing between Europeans and non-European peoples.
* Nouveau
Newly arrived/developed.
* Salient
The most noticeable/important.
* Torpor
State of physical or mental inactivity; lethargy.
* Callousness
/ˈkaləsnəs/
Бессердечность.
Insensitive and cruel disregard for others.
* Jot
Write (something) down quickly
* Avid
Алчный.
* Shunned
Persistently avoided.
* Shyster
/ˈʃʌɪstə/
A person who uses unscrupulous, fraudulent, or deceptive methods in business.
* Turgid
/ˈtəːdʒɪd/
1. Swollen and distended or congested. опухший
2. (of language or style) tediously pompous or bombastic. напыщенный
* Macabra
/məˈkɑːbr(ə)/
Disturbing because concerned with a fear of death.
* Heed
Внимание.
* Corporeal
/kɔːˈpɔːrɪəl/
Relating to a person's body, especially as opposed to spirit.
Having a body. Material.
* Compartment
/kəmˈpɑːtm(ə)nt/
Separate section or part of a structure or container.
* Precarious
/prɪˈkɛːrɪəs/
Not securely held or in position; dangerously likely to fall or collapse.
Сомнительно, ненадёжно.
* Scaffold
Cтроительные леса.
* Gazebo
Беседка, альтанка.
* Vicarious
Experienced through the feelings or actions of another person.
* Gallbladder
Желчный пузырь.
* Bile
Желчь.
* Имманентное
Имманентное - внутренне присущее тому или иному предмету, явлению или процессу свойство (закономерность).
Имманентное - неотьемлемая внутренняя деталь, остающийся внутри границ возможного опыта.
* Деизм
Деизм - философское направление, признающее существование Бога и сотворение им мира, но отрицающее большинство сверхъестественных и мистических явлений.
* Hindsight
Understanding of a situation or event only after it has happened or developed.
* Eavesdrop
Secretly listen to a conversation.
* Expat
Expat - person taking up residency in another country.
* Loam
/ləʊm/
Loam - fertile soil of clay and sand containing humus.
* Mischievous
/ˈmɪstʃɪvəs/
Вредный.
* Terse
Terse - sparing in the use of words; abrupt.
Краткий
* Ubiquitous
Ubiquitous - present, appearing, or found everywhere.
Вездесущий, повсеместный.
* Ravenous
Extremely hungry.
* Neologism
A newly coined word or expression.
* Spitball
Throw out (a suggestion) for discussion.
* Hense
Следовательно.
Therefore.
* Cootie
Платяная вошь.
* Pet peeve
Something that a particular person finds especially annoying.
* Candid
Truthful and straightforward.
* Id
The part of the mind in which innate instinctive impulses and primary processes are manifest.
* Truism
Truism - a statement that is obviously true and says nothing new or interesting.
* Illustrious
Illustrious - famous, well known, respected, and admired for past achievements.
* Befriend
Befriend - become a friend with, especially help people.
* Visceral
Visceral - bringing deep invard emotional feelings.
* Buttermilk
Пахта.
* Silicon
Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre; and it is a tetravalent metalloid and semiconductor.
* Silicone
Silicones, also known as polysiloxanes, are polymers that include any inert, synthetic compound made up of repeating units of siloxane, which is a chain of alternating silicon atoms and oxygen atoms, combined with carbon, hydrogen, and sometimes other elements. They are typically heat-resistant and either liquid or rubber-like, and are used in sealants, adhesives, lubricants, medicine, cooking utensils, and thermal and electrical insulation.
* Artisan
A craftsman of the skilled trade.
* Кондовый
Топорный, грубый, плотно-древесный.
* Heist
Кража.
* Oliebol
Oliebol is a traditional Dutch and Belgian food. Oliebollen are a variety of dumpling made by using an ice cream scoop or two spoons to scoop a certain amount of dough and dropping the dough into a deep fryer filled with hot oil.
* Dissolution
Dissolution - closing down or dismissal of an assembly, partnership, or official body.
Dissolution - debauched living; dissipation.
* Invaluable
/ɪnˈvaljʊ(ə)b(ə)l/
Invaluable - extremely useful; indispensable.
* Morrow
/ˈmɒrəʊ/
Morrow - the time following the event. The following day. The near future.
* Facetious
/fəˈsiːʃəs/
Facetious - treating serious issues with deliberately inappropriate humor; flippant.
* Rhubarb
Rhubarb - ревень.
* Camomile
Camomile - ромашка.
* Embezzler
Embezzler - who takes company money for his or her own purposes.
* Mull
/mʌl/
Mull - think about (a fact, proposal, or request) deeply and at length.
* Innocuous
/ɪˈnɒkjʊəs/
Safe and unharmful.
* Apothecary
Apothecary - a person who prepares medicines and drugs from components.
