* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Mulberry
Шелковица.
* Obligatory
Обязательный.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Сулема
Mercuric chloride. Neurotoxic.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Bagel
Бублик.
* Invective
Critic is the strict sence.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
* CliffsNotes
Short good description of the literature.
Initially CliffNotes are a company and a series of study guides available firstly in the US.
* Abridgment
A shortened version of a larger work.
* Штуцер
1. Ружье с укороченным нарезным стволом через которое и заряжающееся.
Штуцер - неметское слово, позже в обиходе появились слова винтовая пищаль и винтовка.

2. Короткая соединительная труба.
* Хлопуша
Врунишка.
* Ирокез
1. Индеец группы
2. Причёска
* Накипень
Бугор льда из ключа/теплого ключа.
* Фронтон
Венчание фронтальной стены фасада здания, начинаеться за карнизом, обычно теругольное реже - полуциркульное.
* Поносность
Дальнобойность.
* Сполитично
Удобно.
* Орочоне
Некоторые.
* Шустование
Сглаживание дула в рушьях.
* Crepuscular
Cумеречно.
* Excavate
/ˈɛkskəveɪt/
Remove earth from an area to find buried.
* Квартерон
Четверть генов чёрной крови.
* Манишка
Нагрудная вставка в мужской и женской одежде, которая видна в вырезе жилета, фрака или дамского платья.
* Safeword
No comments.
* Flash flood
Внезапный ливневый затапливающий паводок.
* To hoard
Accumulate (money or valued objects) and hide / store away.
* Hardship
Severe suffering or privation.
* Privation
State in which essentials for well-being are lacking.
* Capricious
Changing according to no discernible rules; unpredictable
* Discern
Recognize or find out, distinguish (someone or something) with difficulty by sight or with the other senses.
* Wedlock
The state of being married.
* The Holocene
Current geneological epoch. Began approximately 11,650 cal years before present, after the last glacial period.
* Malcontent
Dissatisfied, complaining, trouble, rebellious.
* Rousing
Воодушевляющий.
Exciting; stirring.
* Rabble
Сброд, чернь.
A disorderly crowd; a mob.
* Contempt
The feeling that a person or a thing is beneath consideration, worthless, or deserving scorn.
* Scorn
Презрение.
* Derision
/dɪˈrɪʒ(ə)n/
Осмеяние.
Contemptuous ridicule or mockery.
* Eggnog
A drink made from a mixture of beaten eggs, cream, and flavorings, often with alcohol
* Malfeasance
Злодеяние, должностоное преступление.
* Indiginous
Mестный.
Native.
* Infatuated
Be inspired with an intense but short-lived passion or admiration for
* Creole
Ethnic groups which originated during the colonial-era from racial mixing between Europeans and non-European peoples.
* Nouveau
Newly arrived/developed.
* Salient
The most noticeable/important.
* Torpor
State of physical or mental inactivity; lethargy.
* Callousness
/ˈkaləsnəs/
Бессердечность.
Insensitive and cruel disregard for others.
* Jot
Write (something) down quickly
* Avid
Алчный.
* Shunned
Persistently avoided.
* Shyster
/ˈʃʌɪstə/
A person who uses unscrupulous, fraudulent, or deceptive methods in business.
* Turgid
/ˈtəːdʒɪd/
1. Swollen and distended or congested. опухший
2. (of language or style) tediously pompous or bombastic. напыщенный
* Macabra
/məˈkɑːbr(ə)/
Disturbing because concerned with a fear of death.
* Heed
Внимание.
* Corporeal
/kɔːˈpɔːrɪəl/
Relating to a person's body, especially as opposed to spirit.
Having a body. Material.
* Compartment
/kəmˈpɑːtm(ə)nt/
Separate section or part of a structure or container.
* Precarious
/prɪˈkɛːrɪəs/
Not securely held or in position; dangerously likely to fall or collapse.
Сомнительно, ненадёжно.
* Scaffold
Cтроительные леса.
* Gazebo
Беседка, альтанка.
* Vicarious
Experienced through the feelings or actions of another person.
* Gallbladder
Желчный пузырь.
* Bile
Желчь.
* Имманентное
Имманентное - внутренне присущее тому или иному предмету, явлению или процессу свойство (закономерность).
Имманентное - неотьемлемая внутренняя деталь, остающийся внутри границ возможного опыта.
* Деизм
Деизм - философское направление, признающее существование Бога и сотворение им мира, но отрицающее большинство сверхъестественных и мистических явлений.
* Hindsight
Understanding of a situation or event only after it has happened or developed.
* Eavesdrop
Secretly listen to a conversation.
* Expat
Expat - person taking up residency in another country.
* Loam
/ləʊm/
Loam - fertile soil of clay and sand containing humus.
* Mischievous
/ˈmɪstʃɪvəs/
Вредный.
* Terse
Terse - sparing in the use of words; abrupt.
Краткий
* Ubiquitous
Ubiquitous - present, appearing, or found everywhere.
Вездесущий, повсеместный.
* Ravenous
Extremely hungry.
* Neologism
A newly coined word or expression.
* Spitball
Throw out (a suggestion) for discussion.
* Hense
Следовательно.
Therefore.
* Cootie
Платяная вошь.
* Pet peeve
Something that a particular person finds especially annoying.
* Candid
Truthful and straightforward.
* Id
The part of the mind in which innate instinctive impulses and primary processes are manifest.
* Truism
Truism - a statement that is obviously true and says nothing new or interesting.
* Illustrious
Illustrious - famous, well known, respected, and admired for past achievements.
* Befriend
Befriend - become a friend with, especially help people.
* Visceral
Visceral - bringing deep invard emotional feelings.
* Buttermilk
Пахта.
* Silicon
Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre; and it is a tetravalent metalloid and semiconductor.
* Silicone
Silicones, also known as polysiloxanes, are polymers that include any inert, synthetic compound made up of repeating units of siloxane, which is a chain of alternating silicon atoms and oxygen atoms, combined with carbon, hydrogen, and sometimes other elements. They are typically heat-resistant and either liquid or rubber-like, and are used in sealants, adhesives, lubricants, medicine, cooking utensils, and thermal and electrical insulation.
* Artisan
A craftsman of the skilled trade.
* Кондовый
Топорный, грубый, плотно-древесный.
* Heist
Кража.
* Oliebol
Oliebol is a traditional Dutch and Belgian food. Oliebollen are a variety of dumpling made by using an ice cream scoop or two spoons to scoop a certain amount of dough and dropping the dough into a deep fryer filled with hot oil.
* Dissolution
Dissolution - closing down or dismissal of an assembly, partnership, or official body.
Dissolution - debauched living; dissipation.
* Invaluable
/ɪnˈvaljʊ(ə)b(ə)l/
Invaluable - extremely useful; indispensable.
* Morrow
/ˈmɒrəʊ/
Morrow - the time following the event. The following day. The near future.
* Facetious
/fəˈsiːʃəs/
Facetious - treating serious issues with deliberately inappropriate humor; flippant.
* Rhubarb
Rhubarb - ревень.
* Camomile
Camomile - ромашка.
* Embezzler
Embezzler - who takes company money for his or her own purposes.
* Mull
/mʌl/
Mull - think about (a fact, proposal, or request) deeply and at length.
* Innocuous
/ɪˈnɒkjʊəs/
Safe and unharmful.
* Apothecary
Apothecary - a person who prepares medicines and drugs from components.
* Materia medica
Materia medica - сумма знаний о лечебный свойствах веществ.
* Foil
Foil - prevent something considered wrong from succeeding.
* Venison
Venison - is the meat of a deer.
* Perch
Жердь, окунь.
* Stern
Stern - корма.
* Peril
Peril - direct serious danger.
* Tick off
Tick off - set a done mark, or to annoy.
* Flay
Flay - strip the skin.
* Arboretum
Arboretum - дендрарий.
* Hardwood
Hardwood - твердые породы деррева.
* Аустерия
Аустерия - от лат. /austeria/ трактир - модный трактир времени Петра.
* Anxious
Anxious - /ˈaŋ(k)ʃəs/ - feeling or showing worry, nervousness, or unease about something with an uncertain outcome.
* Futility
Futility - /fjʊˈtɪlɪti,fjuːˈtɪlɪti/ - pointlessness or uselessness.
Тщетность.
* Pugnacious
Pugnacious - /pʌɡˈneɪʃəs/ - eager to fight, quick to argue, quarrel.
* Epistemology
Epistemology - /ɪˌpɪstɪˈmɒlədʒi,ɛˌpɪstɪˈmɒlədʒi/ - the theory of knowledge, especially with regard to its methods, validity, and scope, and the distinction between justified belief and opinion.
* Resilient
Resilient - /rɪˈzɪlɪənt/ - able to withstand, or quick to recover.
* Hedonism
 Hedonism - /ˈhiːd(ə)nɪz(ə)m,ˈhɛːd(ə)nɪz(ə)m/ - the pursuit of pleasure; sensual self-indulgence.
The ethical theory that pleasure (in the sense of the satisfaction of desires) is the highest good and proper aim of human life.
* Epicureanism
Epicureanism - Epicurus believed that what he called "pleasure" (ἡδονή) was the greatest good, but that the way to attain such pleasure was to live modestly, to gain knowledge of the workings of the world, and to limit one's desires. This would lead one to attain a state of tranquility (ataraxia) and freedom from fear as well as an absence of bodily pain (aponia). The combination of these two states constitutes happiness in its highest form.
* Preemie
Preemie - /ˈprēmē/ - prematurely born baby.
* Jaded
Jaded - /ˈdʒeɪdɪd/ - bored, lacking enthusiasm, after having had too much of something.
* Courtship
Courtship - /ˈkɔːtʃɪp/ - a period of a couple develop before getting married.
* Succinct
Succinct - /sə(k)ˈsiNG(k)t/ - consice, краткий, сжатый.
* Auxiliary
Auxiliary - /ɔːɡˈzɪlɪəri,ɒɡˈzɪlɪəri/ - всомогательный.
* Secular
Secular - /ˈsɛkjʊlə/ - (of clergy) not subject to or bound by religious rule; not belonging to or living in a monastic or other order.
* Sufism
Sufism - . - "Islamic mysticism", "the inward dimension of Islam".
* Bog
Bog - /bɒɡ/ - топь.
* Wart
Wart - /wôrt/ - бородавка.
* Quagmire
Quagmire - /ˈkwaɡmʌɪə/ - трясина.
* Diuretic
Diuretic - . - substance that increases the amount of water and salt expelled.
* Gist
Gist - . - the substance of a speech, text, action.
* Savant
Savant - . - a person of learning. Especially one with detailed knowledge in specialized field. 
* Gnarly
Gnarly - . - slang term for something grotesque, yet awesomely extreme. Used in bad and good cases.
* Cunning
Cunning - . - skill in achieving one's ends by deceit.
* Buffet
Buffet - . - (especially of wind or waves) strike repeatedly and violently; batter.
* Pow wow
Pow wow - . - (from Native Amirican) social gathering. Powwaw - spiritual leader.
* Fathometer
Fathometer - /faˈðɒmɪtə/ - эхолот.
* Bullpen
Bullpen - /ˈbʊlpɛn/ - кутузка.
* Dilligent
Dilligent - /ˈdɪlɪdʒ(ə)nt/ - старательно.
* Succulent
Succulent - /ˈsʌkjʊl(ə)nt/ - 1. tender, juicy, tasty. 2. (of a plant, especially a xerophyte) having thick fleshy leaves or stems adapted to storing water.
* Jinx
Jinx - /dʒɪŋks/ - cursed, bring bad luck.
* Mulligan
Mulligan - /dʒɪŋks/ - is a second chance to perform an action, usually after the first chance went wrong through bad luck or a blunder. 
* Compartmentalize
Compartmentalize - /kɒmpɑːtˈmɛnt(ə)lʌɪz/ - divide into discrete sections or categories.
* Vigilant
Vigilant - /ˈvɪdʒɪl(ə)nt/ - carefully watch.
* Insulary
Insulary - /in·​su·​lary/ - archaic: islander, insular.
* Ancillary
Ancillary - /anˈsɪləri/ - providing necessary support to the primary activities or operation of an organization, system, etc.
* Arson
Arson - /ˈɑːs(ə)n/ - the act of deliberately setting on fire.
* Freebie
Freebie - /ˈfriːbi/ - a thing given free of charge. Халява.
* Indefinite
Indefinite - /ɪnˈdɛfɪnət/ - неопределенный или неограниченный. Размытый.
* Carnal
Carnal - /ˈkɑːn(ə)l/ - плотский.
* Defer
Defer - /dɪˈfəː/ - postpone.
* Sideburns
Sideburns - . - a strip of hair grown by a man down each side of the face in front of his ears.
* Instrumental violence
Instrumental violence - . - is goal-oriented aggression or violence that occurs as a by-product of an individual's attempting to achieve a superordinate goal.
* Incomprehensible
Incomprehensible - /ˌɪnkɒmprɪˈhɛnsɪb(ə)l/ - непостижимо, непонятно, неразборчиво.
* Stail
Stail - /steɪl/ - old form for Stale - no longer fresh.
* Acerbic
Acerbic - /əˈsəːbɪk/ - (especially on a style of speaking) sharp and forthright.
* Outspoken
Outspoken - /aʊtˈspəʊk(ə)n/ - откровенный, прямой.
* Forthright
Forthright - /ˈfɔːθrʌɪt,fɔːθˈrʌɪt/ - (of a person, their manner or speech) direct and outspoken.
* Deadnaming
Deadnaming - . - use name that person changes.
* Preposterous
Preposterous - /prɪˈpɒst(ə)rəs/ - utterly absurd or ridiculous.
* Panspermia
Panspermia - . - principle of life spreading through cosmos due to luck anabiosis and chunks of matter traveling through space.
* Tardigrade
Tardigrade - /ˈtɑːrdɪˌɡreɪd/ - a small living organism also known as water bears that are the most abundant and most durable form of life. Can go into anabiosis in the space.
* Benign
Benign - /bɪˈnʌɪn/ - (of disease) not harmful in effect. Gentle and kind.
* Languid
Languid -  /ˈlaŋ-gwəd/ - сильно уставши.
* Caress
Caress - /kəˈrɛs/ - ласкать, приласкивать.
* Swoon
Swoon - /swuːn/ - faint from extreme emotion.
* Molar
Molar - /ˈməʊlə/ - моляр, коренной зуб.
* Felicitations
Felicitations - /fəlɪsɪˈteɪʃ(ə)nz/ - Words expressing praise for an achievement or good wishes on a special occasion.
* Marooned
Marooned - .  - isolated, abandoned.
* Contrite
Contrite - /kənˈtrʌɪt,ˈkɒntrʌɪt/ - сокрушаться, каяться.
* Fringe
Fringe - /frɪn(d)ʒ/ - дополнательный край, чёлка, бахрома.
* Munition
Munition - /mjʊˈnɪʃ(ə)n/ - военное снаряжение.
* Dispersal
Dispersal - /dɪˈspəːs(ə)l/ - распространение, рассеивание, рассредоточение.
* Discordant
Discordant - /dɪˈskɔːd(ə)nt/ - рассогласованный.
* Accoutrement
Accoutrement - /əˈkuːtəm(ə)nt,əˈkuːtrəm(ə)nt/ - личное снаряжение.
* Prowl
Prowl - /praʊl/ - рыскать.
* Hereditary
Hereditary - /hɪˈrɛdɪt(ə)ri/ - наследственный.
* Man of the cloth
Man of the cloth - .  - clergymen.
* Betrothal
Betrothal - /bɪˈtrəʊð(ə)l/ - помолвка.
* Buck
Buck - /bʌk/ - брыкаться, самец.
* Changeling
Changeling - /ˈtʃeɪn(d)ʒlɪŋ/ - подменыш.
* Amok
Amok - . - killing madness.
* Sage
Sage - . - шалфей, глубокомысленный.
* Indoctrinate
Indoctrinate - /ɪnˈdɒktrɪneɪt/ - внушать.
* Ruth
Ruth - /ruːθ/ - жалость, милосердие, сострадание.
* Burpee
Burpee - /ˈbəːpiː/ - a exercise consisting of a squat thrust made from and ending in a standing position.
* Misogynist
Misogynist - /mɪˈsɒdʒ(ə)nɪst/ - женоненавистник.
* Tardy
Tardy - /ˈtɑːdi/ - запоздалый.
* Feisty
Feisty - /ˈfʌɪsti/ - (of a person, typically one who is relatively small) lively, determined, and courageous.
* Efficacious
Efficacious - /ˌɛfɪˈkeɪʃəs/ - having the power to produce a desired effect.
* Reconnaissance
Reconnaissance - /rɪˈkɒnɪs(ə)ns/ - military observation of a region to locate an enemy or ascertain strategic features.
* Handspring
Handspring - /ˈhan(d)sprɪŋ/ - колесо (елемент).
* Formidable
Formidable - /ˈfɔːmɪdəb(ə)l,fəˈmɪdəb(ə)l/ - inspiring fear or respect through being impressively large, powerful, intense, or capable.
* Reciprocity
Reciprocity - /ˌrɛsɪˈprɒsɪti/ - exchanging things with others for mutual benefit.
* Maw
Maw - /mɔː/ - пасть.
* Veer
Veer - /vɪə/ - a sudden change of direction. Вираж.
* Matte
Matte - /mat/ - штейн, матовая поверхность, маска, каше, декорация.
* Вяхирь
Вяхирь - . - лесной голубь.
* Zesty
Zesty - . - spicy, fun and exciting. Crowd, party, food - everything can be zasty.
* Pungent
Pungent - /ˈpʌn(d)ʒ(ə)nt/ - having a sharply strong taste or smell.
* Banister
Banister - .  - перила, баллюстрада.
* Perverse
Perverse - /pəˈvəːs/ - извращенный.
* Alacrity
Alacrity - /əˈlakrɪti/ - brisk and cheerful readiness.
* Fortuitous
Fortuitous - /fɔːˈtjuːɪtəs/ - by a lucky chance.
* Resourceful
Resourceful - /rɪˈsɔːsfʊl,rɪˈzɔːsfʊl/ - having the ability to find quick and clever ways to overcome difficulties. Находчивый.
* Confounded
Confounded - /kənˈfaʊndɪd/ - cause surprise or confusion in (someone), especially by not according with their expectations.
* Shrill
Shrill - /ʃrɪl/ - high-pitched and piercing.
* Hail
Hail - /heɪl/ - град, в т.ч. звук.
* Slander
Slander - /ˈslɑːndə/ - клевета.
* Anguish
Anguish - /ˈaŋɡwɪʃ/ - особенно остаря тоска.
* Buckle
Buckle - /ˈbʌk(ə)l/ - to bend and give way.
* Brooding
Brooding - /ˈbruːdɪŋ/ - высиживать (яйца), быть глубоко задумчивым.
* Lass
Lass - /las/ - tender calling for a young women.
