* Neophyte
A person who is new to a subject, skill, or belief.
* Nepotism
The practice of favoring relatives or friends, especially by giving them jobs.
* Nomad
A member of a people having no permanent abode, and who travel from place to place to find fresh pasture for their livestock.
* Mulberry
Шелковица.
* Obligatory
обязательный.
* Inuit
The Inuit languages are part of the Eskimo-Aleut family.
* Сулема
Mercuric chloride. Neurotoxic.
* Lemongrass
Лимонное сорго широко используется в качестве приправы в азиатской и карибской кулинариях. Оно обладает цитрусовым ароматом, может быть высушено, смолото, может использоваться свежим. 
* Decanter
Vessel for decantation (keeping liquid still, so it forms solid residue).
* Porron
Strange looking vessel with long nose to drink wine remotely from vessel by drinking stream that shoots from the vessel.
Great for communal wine consumption.
Originated in Catalonia.
* Bagel
Бублик.
* Invective
Critic is the strict sence.
* Idempotence
Property of operation and object to result in the same outcome, despite nested application of operation to object.
